import { ClientProvider } from "@/api";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Toaster />
        <ClientProvider>
          <ReactQueryDevtools initialIsOpen={false} />

          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
